# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import libs/benchmark, strutils

var
  sum: int = 0
  fib = [1,1,2]

benchmark "runtime":
  while fib[2] <= 4_000_000:
    if (fib[2] mod 2 == 0):
      sum += fib[2]
    fib[0] = fib[1]
    fib[1] = fib[2]
    fib[2] = fib[0] + fib[1]

  echo "Result: " & repr(sum)